language: cpp
sudo: required
dist: bionic
install: make get-deps
notifications:
    email: false
compiler:
    - gcc
os:
    -linux

script:
    - ./configure && make && make check && sudo make install && sudo ldconfig && make check-install
