language: cpp
sudo: required
dist: bionic
install: make get-deps
notifications:
    email: false
compiler:
    - gcc
    - clang
os:
    - linux
    - osx

script:
    - ./configure
    - make
    - make check
    - sudo make install
    - make check-install
    - sudo make uninstall
